[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "liblta"
version = "3.1.0"
authors = [
    {name = "NicolÃ¡s Avalos", email = "nicolaseavalos@gmail.com"},
]
description = "A python API to send commands to the LTA (Low-Threshold Acquisition) board."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    'numpy', 
    'pandas',
    'astropy',
]

[project.urls]
Repository = "https://gitlab.com/nicolaseavalos/liblta"