# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gdmty-django-users"
version = "24.5.3"
description = "Extension of Django's AbstractBaseUser for user management, using email as user."
readme = "README.md"
authors = [{ name="Gobierno de Monterrey", email="cesar.benjamin@monterrey.gob.mx" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Framework :: Django",
    "Framework :: Django :: 4",
]
keywords = ["django", "recaptcha", "users"]
dependencies = [
    "django>=4.1.13",
    "djangorestframework",
    "tomli; python_version < '3.11'",
]

requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
"Homepage" = "https://github.com/gobiernodigitalmonterrey/gdmty-django-users"
"Bug Tracker" = "https://github.com/gobiernodigitalmonterrey/gdmty-django-users/issues"

[tool.bumpver]
current_version = "24.5.3"
version_pattern = "MAJOR.MINOR.PATCH[-PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"']
"src/gdmty_django_users/__init__.py" = ["{version}"]