[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lambda_genai_util"
version = "0.0.5"
authors = [
  { name="Biprajeet Kar", email="biprokvs@gmail.com" },
]
maintainers = [
  {name="Biprajeet Kar", email="biprokvs@gmail.com"}
]
description = "Library for GenAI Utility for AWS Based development"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE.txt"}
dependencies = [
  "click"
]