[tool.poetry]
name = "pinnacle-cli"
version = "0.0.2a2"
description = ""
authors = ["Ivan Zhang <ivanzhangofficial@gmail.com>"]
readme = "README.md"
include = ["pinnacle_cli/js/node_modules/**/*"]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
fastapi = "^0.111.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pinnacle = "pinnacle_cli.main:main"
