[tool.poetry]
name = "tuyul-sdk"
version = "0.0.1rc6"
description = ""
authors = ["Antoni Oktha Fernandes <37358597+DesKaOne@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "tuyul_sdk"}]

[tool.poetry.dependencies]
python = "^3.8"
pycryptodomex = "^3.20.0"
colorama = "^0.4.6"
sqlalchemy = "^2.0.30"
sqlalchemy-utils = "^0.41.2"
random-user-agent = "^1.0.1"
base58 = "^2.1.1"
requests = "2.31.0"
httpx = {extras = ["http2","socks"], version = "0.27.0"}
chardet = "^5.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
