[project]
name = "websc-client"
version = "1.0.2"
authors = [
  { name="Patrik Kratochvil", email="info@ledsc.eu" },
]
description = "Library for communicate with websc"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'websockets~=12.0'
]

[project.urls]
homepage = "https://ledsc.eu/websc/"
repository = "https://gitlab.com/ledsc/websclient"
