[tool.poetry]
name = "rockai-cli-app"
version = "0.2.10"
description = "Python SDK for RockAI.online"
authors = ["RockAI <some_developer@example.com>"]
readme = "README.md"
include = ["./rockai_cli_app/docker/tf_compat.json","./rockai_cli_app/docker/torch_compat.json"]

[tool.poetry.scripts]
rock = "rockai_cli_app.rock:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.9.0"}
fastapi = "^0.109.2"
uvicorn = {extras = ["standard"], version = "^0.27.0.post1"}
requests = "^2.31.0"
sseclient = "^0.0.27"
httpx = "^0.27.0"
httpx-sse = "0.1.0"
aiosseclient = "^0.1.3"
aiohttp-sse-client = "0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
