[build-system]
requires = ["hatchling", "pkginfo >= 1.10"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/miml", "src/miml/*"]

[metadata]
version = "1.0.7"
name = "mimllearning"

[project]
name = "mimllearning"
version = "1.0.7"
authors = [
  { name="Damian Martinez", email="damianmartinezavila@gmail.com" },
]
description = "MIML Learning Library"
license = "GPL-3.0"
keywords = ["machine-learning", "python", "data-science", "miml", "multilabel", "multi-instance"]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/p82maavd/miml"
