[project]
name = "ourchester"
version = "0.1.4"
description = "Add your description here"
authors = [
    { name = "Taylor Monacelli", email = "taylormonacelli@gmail.com" }
]
dependencies = [
    "jinja2>=3.1.3",
    "whoosh>=2.7.4",
    "ivylantern>=0.1.0",
    "fishhoof>=0.0.2",
    "platformdirs>=4.2.2",
]
readme = "README.md"
requires-python = ">= 3.12"

[project.scripts]
ourchester = "ourchester:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "black>=24.2.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ourchester"]

[tool.ruff.lint]
extend-select = ["I"]
