# {# pkglts, pyproject.build
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # , "setuptools-scm"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"  # we don't know if we need it
# #}

# {# pkglts, pyproject.project
[project]  # https://packaging.python.org/en/latest/specifications/pyproject-toml/
name = "greer2018"
version = "1.1.0"
description = "Data and formalisms from Greer et al. (2018)"
readme = "README.rst"
requires-python = ">= 3.9"
license = {text = "cc_by_nc"}
authors = [
    {name = "revesansparole", email = "revesansparole@gmail.com"},
]
maintainers = [
    {name = "revesansparole", email = "revesansparole@gmail.com"},
    {name = "Jerome Chopard", email = "revesansparole@gmail.com"},
]
keywords = [
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
]

[project.optional-dependencies]
doc = [
    "sphinx",
    "sphinx-gallery",
    "sphinx_rtd_theme",
]
dvlpt = [
    "twine",
]
example = [
    "matplotlib",
    "pandas",
    "scipy",
]
script = [
    "graphextract",
    "pandas",
]
test = [
    "coverage",
    "pandas",
    "pytest",
    "pytest-cov",
    "pytest-mock",
]


[project.urls]
repository = "https://gitlab.com/b326/greer2018"
pip = "https://pypi.org/project/greer2018/1.1.0/"
conda = "https://anaconda.org/revesansparole/greer2018"
doc = "https://b326.gitlab.io/greer2018/"
pypi = "https://badge.fury.io/py/greer2018"


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ['*.json', '*.ini', '*.csv', '*.rst', '*.svg', ]

# #}
# {# pkglts, test, after pyproject.project
[tool.pytest.ini_options]
addopts = "--maxfail=2 -rf --cov=greer2018"
# #}

# {# pkglts, pyproject.scripts
[project.scripts]
# #}

# {# pkglts, pyproject.gui_scripts
[project.gui-scripts]
# #}
